name: C Build Workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-11, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build on Ubuntu or macOS
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: make unix

      - name: Install MinGW on Windows
        if: contains(matrix.os, 'windows')
        run: choco install mingw

      - name: Build on Windows
        if: contains(matrix.os, 'windows')
        run: mingw32-make win -k

